config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'info' => 'static_pages#info'

  get 'privacy' => 'static_pages#privacy'

  get 'thankyou' => 'static_pages#thankyou'

  get 'tos' => 'static_pages#tos'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def info
  end

  def privacy
  end

  def thankyou
  end

  def tos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html>
<html>
<head>
  <title>RadialReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

</body>
</html> -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Title and metadata -->
    <meta charset="utf-8">
    <title>Radial</title>
    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
    <meta name="description" content="Conduct peer performance assessments efficiently with Radial">
    <meta name="author" content="RadialWorks">
    <!-- Styles -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <!--<link href="/static/css/bootstrap-responsive.css" rel="stylesheet">-->
    <link href="/static/css/docs.css" rel="stylesheet">
    <link href="/static/js/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="/static/css/custom.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/magnific-popup/magnific-popup.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="/static/js/html5shiv.js"></script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="/static/ico/favicon.ico">
    <!-- Google Analytics -->
    <!--<script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-XXXXX-X']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.locatio  n.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>-->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-44741232-2', 'radialworks.com');
      ga('send', 'pageview');
    </script>
  </head>

  <body data-spy="scroll" data-target=".bs-docs-sidebar">
    <%= yield %>
    <!-------------- CALL TO ACTION -------------->
    <a name="register" id="register"></a>
    <div class="cta">
      <div class="container">
        <div class="marketing" style="color: white; margin-bottom: 80px;">
          <br><br><br>
          <h1 class="hidden-phone"><text id="pop">Developing</text> growth is a <text id="pop">journey</text>.<br><br>Join us on ours.</h1>
          <h2 class="visible-phone"><text id="pop">Actualization</text> is a <text id="pop">journey</text>.<br><br>Join us on ours.</h2>
            <br><br>
            <form class="hidden-phone" action="/register/" method="POST">
              <p><i>Register with your email:</i></p>
              <input id="id_subscription_email" maxlength="250" name="subscription_email" type="email" class="required email" required="True" placeholder="Lets find out if we're right for each other" style="height: 40px; text-align: center; width: 550px;">
              <br><br>
             <!--  <input type="submit" value="Start today" class="btn btn-primary btn-large"> -->
              <%= link_to "Start today", thankyou_path, class: "btn btn-primary btn-large"%>
            </form>
            <form class="visible-phone" action="/register/" method="POST">
              <p><i>Register with your email:</i></p>
              <input id="id_subscription_email" maxlength="250" name="subscription_email" type="email" class="required email" required="True" placeholder="Lets see if we're right for each other" style="height: 40px; text-align: center; width: 240px; display: inline-block">
              <br><br>
              <input type="submit" value="Start today" class="btn btn-primary btn-large">
            </form>
        </div>
      </div>
    </div>
    <!-------------- ARTICLES -------------->
    <!-------------- FOOTER -------------->
    <footer class="footer" style=>
      <a name="footer" id="footer"></a>
      <div class="container">
        <div class="row-fluid">
          <div class="span4" style="text-align: left">
            <h4 class="muted" style="font-size: 18px;">Who we are:</h4><br>
            <p style="margin-bottom: 20px;">Radial commits to maximize every human potential by streamlining professional talent development to allow any organization to amplify growth, profit, and actualization.</p>
            <a href="../" class="logo">
              <img src="/static/img/radial.png" style="max-height: 80px; margin-bottom: 25px;">
            </a>
          </div>
          <div class="span4" style="text-align: left">
            <h4 class="muted" style="font-size: 18px;">Lets hear from you!</h4><br>
            <p>Toll-free: <span style="color:#fff; font-size: 25px;">1-800-123-4567</span></p>
            <p>Phone: 402-123-4567</p>
            <p>Fax: 402-234-5678</p>
            <p style="margin-bottom: 20px;">Email: <a href="mailto:contact@radialworks.com">contact@radialworks.com</a></p>
            <%= link_to "CONTACT US", contact_path, class: "btn btn-inverse btn-large", style: "margin-bottom: 25px;" %>
          </div>
          <div class="span4" style="text-align: left">     
            <form action="/thankyou/" method="POST">
              <h4 class="muted" style="font-size: 18px;">Feedback? Questions?<br> Talk to a real person.</h4><br>
              <input id="id_full_name" maxlength="250" name="full_name" type="text" placeholder="Name">
              <input id="id_email" maxlength="250" name="email" class="required email" type="email" placeholder="E-mail*">
              <textarea id="id_comments" name="comments" required="True" placeholder="Questions/Comments"></textarea>
<!--               <input type="submit" value="Send" class="btn btn-primary" style="display: inline-block"> -->
              <%= link_to "Send", thankyou_path, class: "btn btn-primary", style: "display: inline-block" %>
            </form>
          </div>          
        </div>
        <ul class="footer-links">
          <li><a href="../privacy/">Privacy Policy</a></li>
          <li class="muted">&middot;</li>
          <li><a href="../tos/">Terms of Service</a></li>
          <li class="muted">&middot;</li>
          <li>&copy; Copyright 2013 Radial, Inc. All rights reserved.</li>
        </ul>
      </div>    
    </footer>
    <!-------------- STICKY BAR -------------->
    <div class="sticky-bar">
      <div class="hidden-phone" id="mc_embed_signup" style="padding-top: -20px; padding-left: 30px;">
        <form action="/register/" method="POST">
          <input id="id_subscription_email" maxlength="250" name="subscription_email" type="email" class="required email" required="True" placeholder="Why wait? Get updated." style="margin-bottom: 0px; margin-top: -27px; display: inline-block">
          <!-- <input type="submit" value="Subscribe!" class="btn btn-primary" style="display: inline-block; margin-top: -27px;"> -->
          <%= link_to "Subscribe!", thankyou_path, class: "btn btn-primary", style: "display: inline-block; margin-top: -27px;" %>
          <%= link_to "Contact Us", contact_path, class: "btn btn-primary", style: "display: inline-block; margin-top: -27px;" %>
          <a class="iconsocial in" href="http://www.linkedin.com/company/radial-works" target="_blank" style="display: inline-block; margin-top: 10px;"></a>
          <a class="iconsocial tw" href="https://twitter.com/RadialWorks" target="_blank" style="display: inline-block; margin-top: 10px;"></a>
          <a class="iconsocial fb" href="https://www.facebook.com/pages/Radial/339264716218641" target="_blank" style="display: inline-block; margin-top: 10px;"></a>
          <a class="iconsocial gp" href="https://plus.google.com/114028958260667352075/" target="_blank" style="display: inline-block; margin-top: 10px;"></a>
        </form>
      </div>
      <div class="visible-phone" style="padding-top: 10px; padding-left: 10px;">
        <a class="iconsocial in" href="http://www.linkedin.com/company/radial-works" target="_blank" style="display: inline-block;"></a>
        <a class="iconsocial tw" href="https://twitter.com/RadialWorks" target="_blank" style="display: inline-block;"></a>
        <a class="iconsocial fb" href="https://www.facebook.com/pages/Radial/339264716218641" target="_blank" style="display: inline-block;"></a>
        <a class="iconsocial gp" href="https://plus.google.com/114028958260667352075/" target="_blank" style="display: inline-block;"></a>
      </div>
    </div>
    <!-- Le javascript
    ================================================== -->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/magnific-popup/jquery.magnific-popup.js"></script>
    <!-- MAGNIFIC POPUP INITIATE -->
    <script>$('.popup-vimeo').magnificPopup({ disableOn: 700, type: 'iframe', mainClass: 'mfp-fade', iframe: { patterns: { vimeo: { index: 'vimeo.com/', id: '/', src: '//player.vimeo.com/video/%id%?autoplay=1' }, } } });</script>
    <!-- SMOOTH SCROLL INITIATE -->
    <script>$(document).ready(function(e){ var str= location.hash; var n=str.replace("_temp",""); $('html,body').animate({scrollTop:$(n).offset().top}, 500); });</script>
    <!-- TWITTER TIMELINE INITIATE -->
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <!-- EQUALHEIGHT INITIATE -->
    <script type="text/javascript">$(function(){ $('#equalize').equalHeights(); });</script>
    <script type="text/javascript" src="/static/js/jQuery.equalHeights.js"></script>
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/holder/holder.js"></script>
    <script src="/static/js/google-code-prettify/prettify.js"></script>
    <script src="/static/js/application.js"></script>
    <script src="/static/js/fluidvids.js"></script>
  </body>
</html>

app/views/static_pages/contact.html.erb
<div style="padding: 25px;"></div>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="../" rel="" id="anchor1" class="anchorLink">Radial</a>
      <div id="circle"></div>
      <a href="#register" class="try">Register</a>
      <div class="nav-collapse collapse pull-right">
        <ul class="nav">
          <li class="">
            <a href="../#features" rel="" id="anchor1" class="anchorLink">Features</a>
          </li>
          <li class="">
            <a href="../#testimonial" rel="" id="anchor1" class="anchorLink">Customers</a>
          </li>
          <li class="">
            <a href="../#price" rel="" id="anchor1" class="anchorLink">Pricing</a>
          </li>
    <li class="">
      <a href="http://medium.com/@radialworks" target="_blank">Blog</a>
    </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-------------- NAVBAR CONTACT--------------
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="../" rel="" id="anchor1" class="anchorLink">Radial</a>
      <div id="circle"></div>
      <a href="../signup/" class="try">Try us Free</a>
      <div class="nav-collapse collapse pull-right">
        <ul class="nav">
          <li class="">
            <a href="../features/" rel="" id="anchor1" class="anchorLink">Features</a>
          </li>
          <li class="">
            <a href="../customers/" rel="" id="anchor1" class="anchorLink">Customers</a>
          </li>
          <li class="">
            <a href="../signup/" rel="" id="anchor1" class="anchorLink">Pricing</a>
          </li>
    <li class="">
      <a href="http://medium.com/@radialworks" target="_blank">Blog</a>
    </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-------------- CONTACT US -------------->
<div class="testimonial">
  <div class="container">
    <div class="marketing">
      <h1>Support Center</h1>
      <p class="marketing-byline">Find answers, get help, or just talk to us. We make it easy to get hold of us.</p>
      <div class="row-fluid">
        <div class="span4">
          <h2><i class="fa fa-phone fa-3x" style="color: #0088cc"></i><br>Contact us.</h2>
          <p class="marketing-byline">A few ways to get in touch.</p>
          <div style="text-align: left">
            <p>Toll-free: <span style="font-size: 25px; color: #0088cc">1-800-123-4567</span></p>
            <p>Phone: 402-123-4567</p>
            <p>Fax: 402-234-5678</p>
            <p>Address: <br>1201 Infinity Court,<br>Lincoln, NE 68512</p>
            <p style="margin-bottom: 30px;">Email: <a href="mailto:contact@radialworks.com">contact@radialworks.com</a></p>
          </div>
        </div>
        <div class="span4">
          <h2><i class="fa fa-comments-o fa-3x" style="color: #0088cc"></i><br>Straight to our inbox.</h2>
          <p class="marketing-byline">We always reply in person.</p>
          <form action="/thankyou/" method="POST" style="display: inline-block;">
            <input id="id_full_name" maxlength="250" name="full_name" type="text" required="True" placeholder="Name*">
            <input id="id_email" maxlength="250" name="email" class="required email" type="email" placeholder="Email*">
            <input id="id_organization" maxlength="250" name="organization" type="text" placeholder="Organization">
            <input id="id_address" maxlength="250" name="address" type="text" placeholder="Address">
            <input id="id_city" maxlength="250" name="city" type="text" placeholder="City">
            <input id="id_state" maxlength="2" name="state" type="text" placeholder="State">
            <input id="id_zip_code" maxlength="5" name="zip_code" type="text" placeholder="Zip Code">
            <input id="id_phone" maxlength="30" name="phone" type="text" placeholder="Phone Number">
            <textarea cols="40" id="id_comments" name="comments" rows="5" required="True" placeholder="What can we help you with?*"></textarea>

             <%= link_to "Send", thankyou_path, class: "btn btn-primary btn-large", style: "float: right" %>
          </form>
        </div>
        <div class="span4">
          <h2><i class="fa fa-twitter fa-3x" style="color: #0088cc"></i><br>Or send a Tweet.</h2>
          <p class="marketing-byline">Something to share? Let us hear.</p>
          <a class="twitter-timeline" data-dnt="true"  data-link-color="#0088cc" width="300" height="484" href="https://twitter.com/RadialWorks" data-widget-id="399408349441040385">Tweets by @RadialWorks</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/views/static_pages/info.html.erb
<h1>StaticPages#info</h1>
<p>Find me in app/views/static_pages/info.html.erb</p>

app/views/static_pages/privacy.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="../" rel="" id="anchor1" class="anchorLink">Radial</a>
      <div id="circle"></div>
      <a href="#register" class="try">Register</a>
      <div class="nav-collapse collapse pull-right">
        <ul class="nav">
          <li class="">
            <a href="../#features" rel="" id="anchor1" class="anchorLink">Features</a>
          </li>
          <li class="">
            <a href="../#testimonial" rel="" id="anchor1" class="anchorLink">Customers</a>
          </li>
          <li class="">
            <a href="../#price" rel="" id="anchor1" class="anchorLink">Pricing</a>
          </li>
    <li class="">
      <a href="http://medium.com/@radialworks" target="_blank">Blog</a>
    </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-------------- NAVBAR PRIVACY--------------
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="../" rel="" id="anchor1" class="anchorLink">Radial</a>
      <div id="circle"></div>
      <a href="../signup/" class="try">Try us Free</a>
      <div class="nav-collapse collapse pull-right">
        <ul class="nav">
          <li class="">
            <a href="../features/" rel="" id="anchor1" class="anchorLink">Features</a>
          </li>
          <li class="">
            <a href="../customers/" rel="" id="anchor1" class="anchorLink">Customers</a>
          </li>
          <li class="">
            <a href="../signup/" rel="" id="anchor1" class="anchorLink">Pricing</a>
          </li>
    <li class="">
      <a href="http://medium.com/@radialworks" target="_blank">Blog</a>
    </li>
        </ul>
      </div>
    </div>
  </div>
</div>  
<!-------------- PRIVACY-------------->
<div class="testimonial" style="margin-top: 40px;">
  <div class="container" style="margin-bottom:20px;">
    <div class="marketing">
      <div class="row-fluid">
  <div class="span 6">
    <h1><i class="fa fa-asterisk fa-2x" style="color: #0088cc"></i><br>
        Privacy Policy
    </h1><br><br><br>
    <span style="text-align: left">
    <p>
      Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
    </p>
    <ul>
      <li>
        Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
      </li>
      <li>
        We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.   
      </li>
      <li>
        We will only retain personal information as long as necessary for the fulfillment of those purposes. 
      </li>
      <li>
        We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. 
      </li>
      <li>
        Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. 
      </li>
      <li>
        We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
      </li>
      <li>
        We will make readily available to customers information about our policies and practices relating to the management of personal information. 
      </li>
    </ul>
    <p>
      We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. 
    </p>
    </span>
  </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/thankyou.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="../" rel="" id="anchor1" class="anchorLink">Radial</a>
      <div id="circle"></div>
      <a href="#register" class="try">Register</a>
      <div class="nav-collapse collapse pull-right">
        <ul class="nav">
          <li class="">
            <a href="../#features" rel="" id="anchor1" class="anchorLink">Features</a>
          </li>
          <li class="">
            <a href="../#testimonial" rel="" id="anchor1" class="anchorLink">Customers</a>
          </li>
          <li class="">
            <a href="../#price" rel="" id="anchor1" class="anchorLink">Pricing</a>
          </li>
    <li class="">
      <a href="http://medium.com/@radialworks" target="_blank">Blog</a>
    </li>
        </ul>
      </div>
    </div>
  </div>
</div>    
<!-------------- NAVBAR THANKYOU--------------
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="../" rel="" id="anchor1" class="anchorLink">Radial</a>
      <div id="circle"></div>
      <a href="../signup/" class="try">Try us Free</a>
      <div class="nav-collapse collapse pull-right">
        <ul class="nav">
          <li class="">
            <a href="../features/" rel="" id="anchor1" class="anchorLink">Features</a>
          </li>
          <li class="">
            <a href="../customers/" rel="" id="anchor1" class="anchorLink">Customers</a>
          </li>
          <li class="">
            <a href="../signup/" rel="" id="anchor1" class="anchorLink">Pricing</a>
          </li>
    <li class="">
      <a href="http://medium.com/@radialworks" target="_blank">Blog</a>
    </li>
        </ul>
      </div>
    </div>
  </div>
</div>  
<!-------------- THANKYOU-------------->
<div class="testimonial" style="margin-top: 40px;">
  <div class="container">
    <div class="marketing">
      <h1 class="marketing-byline hidden-phone" style="font-size: 50px;">Danke schön, 谢谢, Tusind tak, Grazie mille, Thank ye, ありがとう, Mersi, Tusen Takk, متشكرم , Dziękuję, ཐུགས་རྗེ་ཆེ་།, Gracies, Спасибо, Kia, Wela'lin, Khublei</h1>
      <h1 class="marketing-byline visible-phone" style="font-size: 30px;">Danke schön, 谢谢, Tusind tak, Grazie mille, Thank ye, ありがとう, Mersi, Tusen Takk, متشكرم , Dziękuję, ཐུགས་རྗེ་ཆེ་།, Gracies, Спасибо, Kia, Wela'lin, Khublei</h1>
      <h1><text id="pop">THANK YOU</text>.</h1>
      <h1 class="marketing-byline" style="font-size: 30px;">Thanks for reaching out to <span style="color: #0088cc;"><a href="../">Radial</a></span>;<br>we take care of our people.<br>Hang tight, we're going to be in touch very soon.</h1>
    </div>
  </div>
</div>